apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |
    cluster.name: es-cluster
    node.name: ${NODE_NAME}

    # 멀티 노드 클러스터
    discovery.seed_hosts:
      - elasticsearch-0.elasticsearch
      - elasticsearch-1.elasticsearch
      - elasticsearch-2.elasticsearch

    cluster.initial_master_nodes:
      - elasticsearch-0
      - elasticsearch-1
      - elasticsearch-2

    node.roles: [ "master", "data", "ingest" ]

    xpack.security.enabled: false

    network.host: 0.0.0.0
    http.port: 9200
    transport.port: 9300

    http.cors.enabled: true
    http.cors.allow-origin: "*"