apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elasticsearch-3node

resources:
  - es-configmap.yaml
  - es-statefulset.yaml
  - es-service-headless.yaml
  - es-service-http.yaml
  - es-service-external-0.yaml
  - es-service-external-1.yaml
  - es-service-external-2.yaml