apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

resources:
  - zookeeper-config.yaml
  - zookeeper-service.yaml
  - zookeeper-statefulset.yaml
  - kafka-service.yaml
  - kafka-external-service.yaml
  - kafka-statefulset.yaml
