apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elasticsearch

resources:
  - es-service.yaml
  - es-service-external.yaml
  - es-deployment.yaml
  - es-configmap.yaml
  - es-pvc.yaml